name: Build and Deploy iCal Feed

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: |
          pip install -r requirements.txt
          python ./build.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
